name: Liquibase Changelog Checks

on: [push]

jobs:
  runchecks:
    name: "Run Liquibase Quality Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: XDelphiGrl/erz-liquibase-github-action@v7.3
        with:
          operation: 'checks run'
          changeLogFile: 'example/changelogs/samplechangelog.h2.sql'
          checksSettingsFile: 'example/changelogs/checksettings-changelog.conf'
          proLicenseKey: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
