name: Liquibase Quality Checks

on: [push]

jobs:
  runchecks:
    name: "Run Liquibase Quality Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: XDelphiGrl/erz-liquibase-github-action@v7.2
        with:
          operation: 'checks run'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          checksSettingsFile: 'checkssettings.conf'
          proLicenseKey: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
