name: Liquibase Database Checks

on: [push]

jobs:
  runchecks:
    name: "Run Liquibase Database QCs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: XDelphiGrl/erz-liquibase-github-action@v7.3
        with:
          operation: 'checks run'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          checksSettingsFile: 'checkssettings-db.conf'
          licenseKey: ${{ secrets.LIQUIBASE_LABS_LICENSE }}
