name: Liquibase Update

on: [pull_request]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Liquibase Update
    steps:
      - name: Install Liquibase
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v4
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}