on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: XDelphiGrl/liquibase-github-action@v7.0
        with:
          operation: 'update'
          classpath: classpath: /liquibase/changelog:/liquibase/classpath
          changeLogFile: samplechangelog.h2.sql
          url: jdbc:h2:file:./H2_project/h2tutorial
          username: liqubase
          password: password
          logLevel: info
