on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: XDelphiGrl/docker@v3.4
      - uses: XDelphiGrl/liquibase-github-action@v1
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: dbuser
          password: letmein
          url: url=jdbc:h2:tcp://localhost:9090/mem:dev