on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ XDelphiGrl }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: XDelphiGrl/liquibase-github-action@v5.0
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: dbuser
          password: letmein
          url: url=jdbc:h2:tcp://localhost:9090/mem:dev