name: Liquibase Update

on: [pull_request,push]

jobs:
  update:
    name: Liquibase Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: XDelphiGrl/liquibase-github-action@v7.3.1
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: ${{ secrets.DBUSERNAME }}
          password: ${{ secrets.DBPASS }}
          url: ${{ secrets.DBURL }}
