on: [push]

jobs:
  test-liquibase-action:
    runs-on: docker.pkg.github.com/xdelphigrl/docker/erz-liquibase-docker:dat-5700
    name: Test Liquibase Action
    steps:
      -
        name: Login to GitHub Package Registry
        uses: XDelphiGrl/login-action@v0.1
        with:
          registry: docker.pkg.github.com
          username: XDelphiGrl
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - uses: XDelphiGrl/login-action@v0.1
      - uses: XDelphiGrl/liquibase-github-action@v5.1
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: dbuser
          password: letmein
          url: url=jdbc:h2:tcp://localhost:9090/mem:dev